### ISSUE TITLE
Libraries are built in MD mode.

### ISSUE THREAD

**Issue by TommInfinite** [Starfield-Reverse-Engineering/CLibSFPluginTemplate#6]
Hello!
For me libraries (CommonLibSF.lib and others) are built in MD mode. Because of that I cannot link a MT library to the project.
Is this intended?

**Comment by ThirdEyeSqueegee** [comment]
Not sure what you mean, the build config for this template applies to how the template is built, not how the library is built. Linking CommonLibSF works fine for me with no changes to the template

**Comment by TommInfinite** [comment]
After running VCPKG libraries are built in
CLibSFPluginTemplate\build\release-msvc\vcpkg_installed\x64-windows-static-**md**
Do you think there is a way to build them in mt mode?

**Comment by ThirdEyeSqueegee** [comment]
Not without modifying how the library builds, which is out of scope for a plugin template that uses the library. Gonna go ahead and close this; feel free to raise an issue in the CommonLibSF repo if you want 

EDIT: btw, that triplet means that the library is linked statically while the CRT is linked dynamically

**Comment by TommInfinite** [comment]
okay. Thanks for your time.
